# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: Intellitrain

on:
  pull_request:

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit

  release:
    name: Release
    uses: ./.github/workflows/release.yml
    secrets: inherit
    needs: [ test ]