name: Release

on:
  workflow_call:

jobs:
  release-node:
    name: Release Node Application
    uses: ./.github/workflows/release-docker.yml
    with:
      docker-image-name: mattncott/burger-bot
    secrets: inherit